# Generated by Django 5.2.7 on 2025-10-25 01:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('capital', models.CharField(blank=True, max_length=64, null=True)),
                ('region', models.CharField(blank=True, max_length=64, null=True)),
                ('population', models.IntegerField()),
                ('currency_code', models.CharField(blank=True, max_length=3, null=True)),
                ('exchange_rate', models.FloatField(blank=True, null=True)),
                ('estimated_gdp', models.FloatField(blank=True, null=True)),
                ('flag_url', models.URLField(blank=True, null=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CountryMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_countries', models.IntegerField()),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
